root = "."
tmp_dir = "{{.Env.AIR_TMP}}"

# Default env: watch the worker and isolate its build artifacts under tmp/worker.
env = [
  "AIR_TARGET=worker",
  "AIR_TMP=tmp/worker"
]

shell = "bash"
shell_args = ["-lc"]

[build]
  cmd = "go build -o ./tmp/app ./cmd/${AIR_TARGET:-worker}"
  bin = "tmp/app"
  include_ext = ["go", "tpl", "tmpl", "html", "sql"]
  exclude_dir = ["tmp", "vendor", "docs"]
  exclude_file = ["*_test.go"]

[log]
  time = true
  color = true

[runner]
  cmd = "./tmp/app"
  dir = "."
  args = []

[misc]
  clean_on_exit = true
